/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncServicesRouteImport } from './routes/api/public/sync-services'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicCheckSaldoRouteImport } from './routes/api/public/check-saldo'
import { Route as ApiPublicHooksRecoverAbandonedRouteImport } from './routes/api/public/hooks/recover-abandoned'

const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncServicesRoute = ApiPublicSyncServicesRouteImport.update({
  id: '/api/public/sync-services',
  path: '/api/public/sync-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckSaldoRoute = ApiPublicCheckSaldoRouteImport.update({
  id: '/api/public/check-saldo',
  path: '/api/public/check-saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRecoverAbandonedRoute =
  ApiPublicHooksRecoverAbandonedRouteImport.update({
    id: '/api/public/hooks/recover-abandoned',
    path: '/api/public/hooks/recover-abandoned',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/privacidade'
    | '/sitemap.xml'
    | '/tiktok'
    | '/api/public/check-saldo'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/hooks/recover-abandoned'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/privacidade'
    | '/sitemap.xml'
    | '/tiktok'
    | '/api/public/check-saldo'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/hooks/recover-abandoned'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/privacidade'
    | '/sitemap.xml'
    | '/tiktok'
    | '/api/public/check-saldo'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/hooks/recover-abandoned'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiktokRoute: typeof TiktokRoute
  ApiPublicCheckSaldoRoute: typeof ApiPublicCheckSaldoRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicSyncServicesRoute: typeof ApiPublicSyncServicesRoute
  ApiPublicHooksRecoverAbandonedRoute: typeof ApiPublicHooksRecoverAbandonedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-services': {
      id: '/api/public/sync-services'
      path: '/api/public/sync-services'
      fullPath: '/api/public/sync-services'
      preLoaderRoute: typeof ApiPublicSyncServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-saldo': {
      id: '/api/public/check-saldo'
      path: '/api/public/check-saldo'
      fullPath: '/api/public/check-saldo'
      preLoaderRoute: typeof ApiPublicCheckSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recover-abandoned': {
      id: '/api/public/hooks/recover-abandoned'
      path: '/api/public/hooks/recover-abandoned'
      fullPath: '/api/public/hooks/recover-abandoned'
      preLoaderRoute: typeof ApiPublicHooksRecoverAbandonedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiktokRoute: TiktokRoute,
  ApiPublicCheckSaldoRoute: ApiPublicCheckSaldoRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicSyncServicesRoute: ApiPublicSyncServicesRoute,
  ApiPublicHooksRecoverAbandonedRoute: ApiPublicHooksRecoverAbandonedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
