/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char126flockDotjsRouteImport } from './routes/~flock[.]js'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as TrafegoRouteImport } from './routes/trafego'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as Promo5reaisRouteImport } from './routes/promo-5reais'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitCreatorRouteImport } from './routes/kit-creator'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as Char126apiAnalyticsRouteImport } from './routes/~api.analytics'
import { Route as FerramentasContadorSeguidoresRouteImport } from './routes/ferramentas.contador-seguidores'
import { Route as DashboardSeoRouteImport } from './routes/dashboard.seo'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicTestTiktokEventRouteImport } from './routes/api/public/test-tiktok-event'
import { Route as ApiPublicSyncVerifiedRouteImport } from './routes/api/public/sync-verified'
import { Route as ApiPublicSyncSmmpanelRouteImport } from './routes/api/public/sync-smmpanel'
import { Route as ApiPublicSyncServicesRouteImport } from './routes/api/public/sync-services'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicLgpdDeleteRouteImport } from './routes/api/public/lgpd-delete'
import { Route as ApiPublicJarvisPipelineRouteImport } from './routes/api/public/jarvis-pipeline'
import { Route as ApiPublicCheckSaldoRouteImport } from './routes/api/public/check-saldo'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicSfxNameRouteImport } from './routes/api/public/sfx.$name'
import { Route as ApiPublicQueueWaitingRouteImport } from './routes/api/public/queue/waiting'
import { Route as ApiPublicQueueReprocessRouteImport } from './routes/api/public/queue/reprocess'
import { Route as ApiPublicQueueConfirmRouteImport } from './routes/api/public/queue/confirm'
import { Route as ApiPublicHooksWaitingWatcherRouteImport } from './routes/api/public/hooks/waiting-watcher'
import { Route as ApiPublicHooksSyncPricingRouteImport } from './routes/api/public/hooks/sync-pricing'
import { Route as ApiPublicHooksSmokeTestRouteImport } from './routes/api/public/hooks/smoke-test'
import { Route as ApiPublicHooksSlaWatcherRouteImport } from './routes/api/public/hooks/sla-watcher'
import { Route as ApiPublicHooksReprocessOneRouteImport } from './routes/api/public/hooks/reprocess-one'
import { Route as ApiPublicHooksRecoverAbandonedRouteImport } from './routes/api/public/hooks/recover-abandoned'
import { Route as ApiPublicHooksReconciliationRouteImport } from './routes/api/public/hooks/reconciliation'
import { Route as ApiPublicHooksBackfillSmmhypeIdsRouteImport } from './routes/api/public/hooks/backfill-smmhype-ids'
import { Route as ApiPublicHooksAutoHealerRouteImport } from './routes/api/public/hooks/auto-healer'
import { Route as ApiPublicAdminPricingConfigRouteImport } from './routes/api/public/admin/pricing-config'

const Char126flockDotjsRoute = Char126flockDotjsRouteImport.update({
  id: '/~flock.js',
  path: '/~flock.js',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafegoRoute = TrafegoRouteImport.update({
  id: '/trafego',
  path: '/trafego',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const Promo5reaisRoute = Promo5reaisRouteImport.update({
  id: '/promo-5reais',
  path: '/promo-5reais',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitCreatorRoute = KitCreatorRouteImport.update({
  id: '/kit-creator',
  path: '/kit-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126apiAnalyticsRoute = Char126apiAnalyticsRouteImport.update({
  id: '/~api/analytics',
  path: '/~api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasContadorSeguidoresRoute =
  FerramentasContadorSeguidoresRouteImport.update({
    id: '/ferramentas/contador-seguidores',
    path: '/ferramentas/contador-seguidores',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/dashboard/seo',
  path: '/dashboard/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestTiktokEventRoute =
  ApiPublicTestTiktokEventRouteImport.update({
    id: '/api/public/test-tiktok-event',
    path: '/api/public/test-tiktok-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncVerifiedRoute = ApiPublicSyncVerifiedRouteImport.update({
  id: '/api/public/sync-verified',
  path: '/api/public/sync-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncSmmpanelRoute = ApiPublicSyncSmmpanelRouteImport.update({
  id: '/api/public/sync-smmpanel',
  path: '/api/public/sync-smmpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncServicesRoute = ApiPublicSyncServicesRouteImport.update({
  id: '/api/public/sync-services',
  path: '/api/public/sync-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLgpdDeleteRoute = ApiPublicLgpdDeleteRouteImport.update({
  id: '/api/public/lgpd-delete',
  path: '/api/public/lgpd-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJarvisPipelineRoute = ApiPublicJarvisPipelineRouteImport.update({
  id: '/api/public/jarvis-pipeline',
  path: '/api/public/jarvis-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckSaldoRoute = ApiPublicCheckSaldoRouteImport.update({
  id: '/api/public/check-saldo',
  path: '/api/public/check-saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSfxNameRoute = ApiPublicSfxNameRouteImport.update({
  id: '/api/public/sfx/$name',
  path: '/api/public/sfx/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueWaitingRoute = ApiPublicQueueWaitingRouteImport.update({
  id: '/api/public/queue/waiting',
  path: '/api/public/queue/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueReprocessRoute = ApiPublicQueueReprocessRouteImport.update({
  id: '/api/public/queue/reprocess',
  path: '/api/public/queue/reprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueConfirmRoute = ApiPublicQueueConfirmRouteImport.update({
  id: '/api/public/queue/confirm',
  path: '/api/public/queue/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWaitingWatcherRoute =
  ApiPublicHooksWaitingWatcherRouteImport.update({
    id: '/api/public/hooks/waiting-watcher',
    path: '/api/public/hooks/waiting-watcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncPricingRoute =
  ApiPublicHooksSyncPricingRouteImport.update({
    id: '/api/public/hooks/sync-pricing',
    path: '/api/public/hooks/sync-pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSmokeTestRoute = ApiPublicHooksSmokeTestRouteImport.update({
  id: '/api/public/hooks/smoke-test',
  path: '/api/public/hooks/smoke-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaWatcherRoute =
  ApiPublicHooksSlaWatcherRouteImport.update({
    id: '/api/public/hooks/sla-watcher',
    path: '/api/public/hooks/sla-watcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReprocessOneRoute =
  ApiPublicHooksReprocessOneRouteImport.update({
    id: '/api/public/hooks/reprocess-one',
    path: '/api/public/hooks/reprocess-one',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecoverAbandonedRoute =
  ApiPublicHooksRecoverAbandonedRouteImport.update({
    id: '/api/public/hooks/recover-abandoned',
    path: '/api/public/hooks/recover-abandoned',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconciliationRoute =
  ApiPublicHooksReconciliationRouteImport.update({
    id: '/api/public/hooks/reconciliation',
    path: '/api/public/hooks/reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillSmmhypeIdsRoute =
  ApiPublicHooksBackfillSmmhypeIdsRouteImport.update({
    id: '/api/public/hooks/backfill-smmhype-ids',
    path: '/api/public/hooks/backfill-smmhype-ids',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoHealerRoute =
  ApiPublicHooksAutoHealerRouteImport.update({
    id: '/api/public/hooks/auto-healer',
    path: '/api/public/hooks/auto-healer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminPricingConfigRoute =
  ApiPublicAdminPricingConfigRouteImport.update({
    id: '/api/public/admin/pricing-config',
    path: '/api/public/admin/pricing-config',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diagnostico': typeof DiagnosticoRoute
  '/facebook': typeof FacebookRoute
  '/kit-creator': typeof KitCreatorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/promo-5reais': typeof Promo5reaisRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/telegram': typeof TelegramRoute
  '/termos': typeof TermosRoute
  '/tiktok': typeof TiktokRoute
  '/trafego': typeof TrafegoRoute
  '/youtube': typeof YoutubeRoute
  '/~flock.js': typeof Char126flockDotjsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/ferramentas/contador-seguidores': typeof FerramentasContadorSeguidoresRoute
  '/~api/analytics': typeof Char126apiAnalyticsRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/jarvis-pipeline': typeof ApiPublicJarvisPipelineRoute
  '/api/public/lgpd-delete': typeof ApiPublicLgpdDeleteRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/sync-smmpanel': typeof ApiPublicSyncSmmpanelRoute
  '/api/public/sync-verified': typeof ApiPublicSyncVerifiedRoute
  '/api/public/test-tiktok-event': typeof ApiPublicTestTiktokEventRoute
  '/api/public/admin/pricing-config': typeof ApiPublicAdminPricingConfigRoute
  '/api/public/hooks/auto-healer': typeof ApiPublicHooksAutoHealerRoute
  '/api/public/hooks/backfill-smmhype-ids': typeof ApiPublicHooksBackfillSmmhypeIdsRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
  '/api/public/hooks/reprocess-one': typeof ApiPublicHooksReprocessOneRoute
  '/api/public/hooks/sla-watcher': typeof ApiPublicHooksSlaWatcherRoute
  '/api/public/hooks/smoke-test': typeof ApiPublicHooksSmokeTestRoute
  '/api/public/hooks/sync-pricing': typeof ApiPublicHooksSyncPricingRoute
  '/api/public/hooks/waiting-watcher': typeof ApiPublicHooksWaitingWatcherRoute
  '/api/public/queue/confirm': typeof ApiPublicQueueConfirmRoute
  '/api/public/queue/reprocess': typeof ApiPublicQueueReprocessRoute
  '/api/public/queue/waiting': typeof ApiPublicQueueWaitingRoute
  '/api/public/sfx/$name': typeof ApiPublicSfxNameRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diagnostico': typeof DiagnosticoRoute
  '/facebook': typeof FacebookRoute
  '/kit-creator': typeof KitCreatorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/promo-5reais': typeof Promo5reaisRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/telegram': typeof TelegramRoute
  '/termos': typeof TermosRoute
  '/tiktok': typeof TiktokRoute
  '/trafego': typeof TrafegoRoute
  '/youtube': typeof YoutubeRoute
  '/~flock.js': typeof Char126flockDotjsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/ferramentas/contador-seguidores': typeof FerramentasContadorSeguidoresRoute
  '/~api/analytics': typeof Char126apiAnalyticsRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/jarvis-pipeline': typeof ApiPublicJarvisPipelineRoute
  '/api/public/lgpd-delete': typeof ApiPublicLgpdDeleteRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/sync-smmpanel': typeof ApiPublicSyncSmmpanelRoute
  '/api/public/sync-verified': typeof ApiPublicSyncVerifiedRoute
  '/api/public/test-tiktok-event': typeof ApiPublicTestTiktokEventRoute
  '/api/public/admin/pricing-config': typeof ApiPublicAdminPricingConfigRoute
  '/api/public/hooks/auto-healer': typeof ApiPublicHooksAutoHealerRoute
  '/api/public/hooks/backfill-smmhype-ids': typeof ApiPublicHooksBackfillSmmhypeIdsRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
  '/api/public/hooks/reprocess-one': typeof ApiPublicHooksReprocessOneRoute
  '/api/public/hooks/sla-watcher': typeof ApiPublicHooksSlaWatcherRoute
  '/api/public/hooks/smoke-test': typeof ApiPublicHooksSmokeTestRoute
  '/api/public/hooks/sync-pricing': typeof ApiPublicHooksSyncPricingRoute
  '/api/public/hooks/waiting-watcher': typeof ApiPublicHooksWaitingWatcherRoute
  '/api/public/queue/confirm': typeof ApiPublicQueueConfirmRoute
  '/api/public/queue/reprocess': typeof ApiPublicQueueReprocessRoute
  '/api/public/queue/waiting': typeof ApiPublicQueueWaitingRoute
  '/api/public/sfx/$name': typeof ApiPublicSfxNameRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diagnostico': typeof DiagnosticoRoute
  '/facebook': typeof FacebookRoute
  '/kit-creator': typeof KitCreatorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/promo-5reais': typeof Promo5reaisRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/telegram': typeof TelegramRoute
  '/termos': typeof TermosRoute
  '/tiktok': typeof TiktokRoute
  '/trafego': typeof TrafegoRoute
  '/youtube': typeof YoutubeRoute
  '/~flock.js': typeof Char126flockDotjsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/ferramentas/contador-seguidores': typeof FerramentasContadorSeguidoresRoute
  '/~api/analytics': typeof Char126apiAnalyticsRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/check-saldo': typeof ApiPublicCheckSaldoRoute
  '/api/public/jarvis-pipeline': typeof ApiPublicJarvisPipelineRoute
  '/api/public/lgpd-delete': typeof ApiPublicLgpdDeleteRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/sync-services': typeof ApiPublicSyncServicesRoute
  '/api/public/sync-smmpanel': typeof ApiPublicSyncSmmpanelRoute
  '/api/public/sync-verified': typeof ApiPublicSyncVerifiedRoute
  '/api/public/test-tiktok-event': typeof ApiPublicTestTiktokEventRoute
  '/api/public/admin/pricing-config': typeof ApiPublicAdminPricingConfigRoute
  '/api/public/hooks/auto-healer': typeof ApiPublicHooksAutoHealerRoute
  '/api/public/hooks/backfill-smmhype-ids': typeof ApiPublicHooksBackfillSmmhypeIdsRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/recover-abandoned': typeof ApiPublicHooksRecoverAbandonedRoute
  '/api/public/hooks/reprocess-one': typeof ApiPublicHooksReprocessOneRoute
  '/api/public/hooks/sla-watcher': typeof ApiPublicHooksSlaWatcherRoute
  '/api/public/hooks/smoke-test': typeof ApiPublicHooksSmokeTestRoute
  '/api/public/hooks/sync-pricing': typeof ApiPublicHooksSyncPricingRoute
  '/api/public/hooks/waiting-watcher': typeof ApiPublicHooksWaitingWatcherRoute
  '/api/public/queue/confirm': typeof ApiPublicQueueConfirmRoute
  '/api/public/queue/reprocess': typeof ApiPublicQueueReprocessRoute
  '/api/public/queue/waiting': typeof ApiPublicQueueWaitingRoute
  '/api/public/sfx/$name': typeof ApiPublicSfxNameRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/facebook'
    | '/kit-creator'
    | '/login'
    | '/mcp'
    | '/obrigado'
    | '/privacidade'
    | '/promo-5reais'
    | '/reembolso'
    | '/sitemap.xml'
    | '/status'
    | '/telegram'
    | '/termos'
    | '/tiktok'
    | '/trafego'
    | '/youtube'
    | '/~flock.js'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/catalog'
    | '/blog/$slug'
    | '/dashboard/seo'
    | '/ferramentas/contador-seguidores'
    | '/~api/analytics'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/check-saldo'
    | '/api/public/jarvis-pipeline'
    | '/api/public/lgpd-delete'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/sync-smmpanel'
    | '/api/public/sync-verified'
    | '/api/public/test-tiktok-event'
    | '/api/public/admin/pricing-config'
    | '/api/public/hooks/auto-healer'
    | '/api/public/hooks/backfill-smmhype-ids'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/recover-abandoned'
    | '/api/public/hooks/reprocess-one'
    | '/api/public/hooks/sla-watcher'
    | '/api/public/hooks/smoke-test'
    | '/api/public/hooks/sync-pricing'
    | '/api/public/hooks/waiting-watcher'
    | '/api/public/queue/confirm'
    | '/api/public/queue/reprocess'
    | '/api/public/queue/waiting'
    | '/api/public/sfx/$name'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/facebook'
    | '/kit-creator'
    | '/login'
    | '/mcp'
    | '/obrigado'
    | '/privacidade'
    | '/promo-5reais'
    | '/reembolso'
    | '/sitemap.xml'
    | '/status'
    | '/telegram'
    | '/termos'
    | '/tiktok'
    | '/trafego'
    | '/youtube'
    | '/~flock.js'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/catalog'
    | '/blog/$slug'
    | '/dashboard/seo'
    | '/ferramentas/contador-seguidores'
    | '/~api/analytics'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/check-saldo'
    | '/api/public/jarvis-pipeline'
    | '/api/public/lgpd-delete'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/sync-smmpanel'
    | '/api/public/sync-verified'
    | '/api/public/test-tiktok-event'
    | '/api/public/admin/pricing-config'
    | '/api/public/hooks/auto-healer'
    | '/api/public/hooks/backfill-smmhype-ids'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/recover-abandoned'
    | '/api/public/hooks/reprocess-one'
    | '/api/public/hooks/sla-watcher'
    | '/api/public/hooks/smoke-test'
    | '/api/public/hooks/sync-pricing'
    | '/api/public/hooks/waiting-watcher'
    | '/api/public/queue/confirm'
    | '/api/public/queue/reprocess'
    | '/api/public/queue/waiting'
    | '/api/public/sfx/$name'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/diagnostico'
    | '/facebook'
    | '/kit-creator'
    | '/login'
    | '/mcp'
    | '/obrigado'
    | '/privacidade'
    | '/promo-5reais'
    | '/reembolso'
    | '/sitemap.xml'
    | '/status'
    | '/telegram'
    | '/termos'
    | '/tiktok'
    | '/trafego'
    | '/youtube'
    | '/~flock.js'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/catalog'
    | '/blog/$slug'
    | '/dashboard/seo'
    | '/ferramentas/contador-seguidores'
    | '/~api/analytics'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/check-saldo'
    | '/api/public/jarvis-pipeline'
    | '/api/public/lgpd-delete'
    | '/api/public/mp-webhook'
    | '/api/public/sync-services'
    | '/api/public/sync-smmpanel'
    | '/api/public/sync-verified'
    | '/api/public/test-tiktok-event'
    | '/api/public/admin/pricing-config'
    | '/api/public/hooks/auto-healer'
    | '/api/public/hooks/backfill-smmhype-ids'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/recover-abandoned'
    | '/api/public/hooks/reprocess-one'
    | '/api/public/hooks/sla-watcher'
    | '/api/public/hooks/smoke-test'
    | '/api/public/hooks/sync-pricing'
    | '/api/public/hooks/waiting-watcher'
    | '/api/public/queue/confirm'
    | '/api/public/queue/reprocess'
    | '/api/public/queue/waiting'
    | '/api/public/sfx/$name'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiagnosticoRoute: typeof DiagnosticoRoute
  FacebookRoute: typeof FacebookRoute
  KitCreatorRoute: typeof KitCreatorRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  Promo5reaisRoute: typeof Promo5reaisRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TelegramRoute: typeof TelegramRoute
  TermosRoute: typeof TermosRoute
  TiktokRoute: typeof TiktokRoute
  TrafegoRoute: typeof TrafegoRoute
  YoutubeRoute: typeof YoutubeRoute
  Char126flockDotjsRoute: typeof Char126flockDotjsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  FerramentasContadorSeguidoresRoute: typeof FerramentasContadorSeguidoresRoute
  Char126apiAnalyticsRoute: typeof Char126apiAnalyticsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCheckSaldoRoute: typeof ApiPublicCheckSaldoRoute
  ApiPublicJarvisPipelineRoute: typeof ApiPublicJarvisPipelineRoute
  ApiPublicLgpdDeleteRoute: typeof ApiPublicLgpdDeleteRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicSyncServicesRoute: typeof ApiPublicSyncServicesRoute
  ApiPublicSyncSmmpanelRoute: typeof ApiPublicSyncSmmpanelRoute
  ApiPublicSyncVerifiedRoute: typeof ApiPublicSyncVerifiedRoute
  ApiPublicTestTiktokEventRoute: typeof ApiPublicTestTiktokEventRoute
  ApiPublicAdminPricingConfigRoute: typeof ApiPublicAdminPricingConfigRoute
  ApiPublicHooksAutoHealerRoute: typeof ApiPublicHooksAutoHealerRoute
  ApiPublicHooksBackfillSmmhypeIdsRoute: typeof ApiPublicHooksBackfillSmmhypeIdsRoute
  ApiPublicHooksReconciliationRoute: typeof ApiPublicHooksReconciliationRoute
  ApiPublicHooksRecoverAbandonedRoute: typeof ApiPublicHooksRecoverAbandonedRoute
  ApiPublicHooksReprocessOneRoute: typeof ApiPublicHooksReprocessOneRoute
  ApiPublicHooksSlaWatcherRoute: typeof ApiPublicHooksSlaWatcherRoute
  ApiPublicHooksSmokeTestRoute: typeof ApiPublicHooksSmokeTestRoute
  ApiPublicHooksSyncPricingRoute: typeof ApiPublicHooksSyncPricingRoute
  ApiPublicHooksWaitingWatcherRoute: typeof ApiPublicHooksWaitingWatcherRoute
  ApiPublicQueueConfirmRoute: typeof ApiPublicQueueConfirmRoute
  ApiPublicQueueReprocessRoute: typeof ApiPublicQueueReprocessRoute
  ApiPublicQueueWaitingRoute: typeof ApiPublicQueueWaitingRoute
  ApiPublicSfxNameRoute: typeof ApiPublicSfxNameRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/~flock.js': {
      id: '/~flock.js'
      path: '/~flock.js'
      fullPath: '/~flock.js'
      preLoaderRoute: typeof Char126flockDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trafego': {
      id: '/trafego'
      path: '/trafego'
      fullPath: '/trafego'
      preLoaderRoute: typeof TrafegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-5reais': {
      id: '/promo-5reais'
      path: '/promo-5reais'
      fullPath: '/promo-5reais'
      preLoaderRoute: typeof Promo5reaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-creator': {
      id: '/kit-creator'
      path: '/kit-creator'
      fullPath: '/kit-creator'
      preLoaderRoute: typeof KitCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~api/analytics': {
      id: '/~api/analytics'
      path: '/~api/analytics'
      fullPath: '/~api/analytics'
      preLoaderRoute: typeof Char126apiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/contador-seguidores': {
      id: '/ferramentas/contador-seguidores'
      path: '/ferramentas/contador-seguidores'
      fullPath: '/ferramentas/contador-seguidores'
      preLoaderRoute: typeof FerramentasContadorSeguidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/dashboard/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-tiktok-event': {
      id: '/api/public/test-tiktok-event'
      path: '/api/public/test-tiktok-event'
      fullPath: '/api/public/test-tiktok-event'
      preLoaderRoute: typeof ApiPublicTestTiktokEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-verified': {
      id: '/api/public/sync-verified'
      path: '/api/public/sync-verified'
      fullPath: '/api/public/sync-verified'
      preLoaderRoute: typeof ApiPublicSyncVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-smmpanel': {
      id: '/api/public/sync-smmpanel'
      path: '/api/public/sync-smmpanel'
      fullPath: '/api/public/sync-smmpanel'
      preLoaderRoute: typeof ApiPublicSyncSmmpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-services': {
      id: '/api/public/sync-services'
      path: '/api/public/sync-services'
      fullPath: '/api/public/sync-services'
      preLoaderRoute: typeof ApiPublicSyncServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lgpd-delete': {
      id: '/api/public/lgpd-delete'
      path: '/api/public/lgpd-delete'
      fullPath: '/api/public/lgpd-delete'
      preLoaderRoute: typeof ApiPublicLgpdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis-pipeline': {
      id: '/api/public/jarvis-pipeline'
      path: '/api/public/jarvis-pipeline'
      fullPath: '/api/public/jarvis-pipeline'
      preLoaderRoute: typeof ApiPublicJarvisPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-saldo': {
      id: '/api/public/check-saldo'
      path: '/api/public/check-saldo'
      fullPath: '/api/public/check-saldo'
      preLoaderRoute: typeof ApiPublicCheckSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sfx/$name': {
      id: '/api/public/sfx/$name'
      path: '/api/public/sfx/$name'
      fullPath: '/api/public/sfx/$name'
      preLoaderRoute: typeof ApiPublicSfxNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/waiting': {
      id: '/api/public/queue/waiting'
      path: '/api/public/queue/waiting'
      fullPath: '/api/public/queue/waiting'
      preLoaderRoute: typeof ApiPublicQueueWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/reprocess': {
      id: '/api/public/queue/reprocess'
      path: '/api/public/queue/reprocess'
      fullPath: '/api/public/queue/reprocess'
      preLoaderRoute: typeof ApiPublicQueueReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/confirm': {
      id: '/api/public/queue/confirm'
      path: '/api/public/queue/confirm'
      fullPath: '/api/public/queue/confirm'
      preLoaderRoute: typeof ApiPublicQueueConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/waiting-watcher': {
      id: '/api/public/hooks/waiting-watcher'
      path: '/api/public/hooks/waiting-watcher'
      fullPath: '/api/public/hooks/waiting-watcher'
      preLoaderRoute: typeof ApiPublicHooksWaitingWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-pricing': {
      id: '/api/public/hooks/sync-pricing'
      path: '/api/public/hooks/sync-pricing'
      fullPath: '/api/public/hooks/sync-pricing'
      preLoaderRoute: typeof ApiPublicHooksSyncPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/smoke-test': {
      id: '/api/public/hooks/smoke-test'
      path: '/api/public/hooks/smoke-test'
      fullPath: '/api/public/hooks/smoke-test'
      preLoaderRoute: typeof ApiPublicHooksSmokeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-watcher': {
      id: '/api/public/hooks/sla-watcher'
      path: '/api/public/hooks/sla-watcher'
      fullPath: '/api/public/hooks/sla-watcher'
      preLoaderRoute: typeof ApiPublicHooksSlaWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reprocess-one': {
      id: '/api/public/hooks/reprocess-one'
      path: '/api/public/hooks/reprocess-one'
      fullPath: '/api/public/hooks/reprocess-one'
      preLoaderRoute: typeof ApiPublicHooksReprocessOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recover-abandoned': {
      id: '/api/public/hooks/recover-abandoned'
      path: '/api/public/hooks/recover-abandoned'
      fullPath: '/api/public/hooks/recover-abandoned'
      preLoaderRoute: typeof ApiPublicHooksRecoverAbandonedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconciliation': {
      id: '/api/public/hooks/reconciliation'
      path: '/api/public/hooks/reconciliation'
      fullPath: '/api/public/hooks/reconciliation'
      preLoaderRoute: typeof ApiPublicHooksReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-smmhype-ids': {
      id: '/api/public/hooks/backfill-smmhype-ids'
      path: '/api/public/hooks/backfill-smmhype-ids'
      fullPath: '/api/public/hooks/backfill-smmhype-ids'
      preLoaderRoute: typeof ApiPublicHooksBackfillSmmhypeIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-healer': {
      id: '/api/public/hooks/auto-healer'
      path: '/api/public/hooks/auto-healer'
      fullPath: '/api/public/hooks/auto-healer'
      preLoaderRoute: typeof ApiPublicHooksAutoHealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/pricing-config': {
      id: '/api/public/admin/pricing-config'
      path: '/api/public/admin/pricing-config'
      fullPath: '/api/public/admin/pricing-config'
      preLoaderRoute: typeof ApiPublicAdminPricingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DiagnosticoRoute: DiagnosticoRoute,
  FacebookRoute: FacebookRoute,
  KitCreatorRoute: KitCreatorRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  Promo5reaisRoute: Promo5reaisRoute,
  ReembolsoRoute: ReembolsoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TelegramRoute: TelegramRoute,
  TermosRoute: TermosRoute,
  TiktokRoute: TiktokRoute,
  TrafegoRoute: TrafegoRoute,
  YoutubeRoute: YoutubeRoute,
  Char126flockDotjsRoute: Char126flockDotjsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  FerramentasContadorSeguidoresRoute: FerramentasContadorSeguidoresRoute,
  Char126apiAnalyticsRoute: Char126apiAnalyticsRoute,
  BlogIndexRoute: BlogIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCheckSaldoRoute: ApiPublicCheckSaldoRoute,
  ApiPublicJarvisPipelineRoute: ApiPublicJarvisPipelineRoute,
  ApiPublicLgpdDeleteRoute: ApiPublicLgpdDeleteRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicSyncServicesRoute: ApiPublicSyncServicesRoute,
  ApiPublicSyncSmmpanelRoute: ApiPublicSyncSmmpanelRoute,
  ApiPublicSyncVerifiedRoute: ApiPublicSyncVerifiedRoute,
  ApiPublicTestTiktokEventRoute: ApiPublicTestTiktokEventRoute,
  ApiPublicAdminPricingConfigRoute: ApiPublicAdminPricingConfigRoute,
  ApiPublicHooksAutoHealerRoute: ApiPublicHooksAutoHealerRoute,
  ApiPublicHooksBackfillSmmhypeIdsRoute: ApiPublicHooksBackfillSmmhypeIdsRoute,
  ApiPublicHooksReconciliationRoute: ApiPublicHooksReconciliationRoute,
  ApiPublicHooksRecoverAbandonedRoute: ApiPublicHooksRecoverAbandonedRoute,
  ApiPublicHooksReprocessOneRoute: ApiPublicHooksReprocessOneRoute,
  ApiPublicHooksSlaWatcherRoute: ApiPublicHooksSlaWatcherRoute,
  ApiPublicHooksSmokeTestRoute: ApiPublicHooksSmokeTestRoute,
  ApiPublicHooksSyncPricingRoute: ApiPublicHooksSyncPricingRoute,
  ApiPublicHooksWaitingWatcherRoute: ApiPublicHooksWaitingWatcherRoute,
  ApiPublicQueueConfirmRoute: ApiPublicQueueConfirmRoute,
  ApiPublicQueueReprocessRoute: ApiPublicQueueReprocessRoute,
  ApiPublicQueueWaitingRoute: ApiPublicQueueWaitingRoute,
  ApiPublicSfxNameRoute: ApiPublicSfxNameRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
